# Generated by Django 2.0.3 on 2018-04-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_auto_20180413_1147'),
        ('ordermanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersdone',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='ordersdone',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='ordersdone',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='ordersdone',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='ordersdone',
            name='cartmanager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.CartManager'),
        ),
    ]
