# Generated by Django 2.0.3 on 2018-04-14 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_auto_20180413_1147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordermanage', '0002_auto_20180413_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(default=0, max_length=10)),
                ('payment', models.CharField(max_length=20)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('item_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cartmanager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordermanage.OrderManager')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Menu')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
