# Generated by Django 2.0.3 on 2018-04-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanage', '0003_ordermanager_ordersconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermanager',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
