# Generated by Django 2.0.3 on 2018-05-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanage', '0004_ordermanager_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermanager',
            name='etc_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordersconfirm',
            name='etc_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ordersdone',
            name='etc_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
