# Generated by Django 2.0.3 on 2018-04-11 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=10)),
                ('area', models.CharField(choices=[('janipur', 'janipur'), ('disco road', 'disco road'), ('Talli morh', 'Talli morh'), ('New Plot', 'New Plot'), ('Ptoli', 'Ptoli'), ('Lower Roop Nagar', 'Lower Roop Nagar'), ('upper roop Nagar', 'Upper Roop Nagar'), ('Old Janipur', 'Old janipur'), ('gandhinagar', 'GandhiNagar'), ('Trikuta Nagar', 'Trikuta Nagar'), ('Amphalaa', 'Amphalla'), ('rehari', 'Rehari')], default='None', max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('pincode', models.CharField(max_length=6)),
                ('land_mark', models.CharField(max_length=30)),
            ],
        ),
    ]
