# Generated by Django 2.0.3 on 2018-04-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tc',
            field=models.BooleanField(default=False),
        ),
    ]
