# Generated by Django 2.0.3 on 2018-04-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20180411_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_on',
        ),
    ]
