# Generated by Django 2.0.3 on 2018-04-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20180413_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='item_price',
        ),
    ]
