# Generated by Django 2.0.3 on 2018-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20180413_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmanager',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
