# Generated by Django 2.0.3 on 2018-04-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_cartmanager_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='cartmanager',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='cartmanager',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartmanager',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='cartmanager',
            name='status',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartmanager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.CartManager'),
        ),
    ]
