# Generated by Django 2.0.3 on 2018-04-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_auto_20180413_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmanager',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
