# Generated by Django 2.0.3 on 2018-04-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_menu_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('dhaba', 'DHABA'), ('cafe', 'CAFE'), ('fast_food', 'FAST FOOD'), ('destination_restaurant', 'DESTINATION RESTAURANT'), ('Street_food', 'street food')], default=None, max_length=40),
        ),
    ]
